name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      
      - name: Display Outputs
        run: |
          echo ${{ steps.semver.outputs.current }}
          echo ${{ steps.semver.outputs.next }}
          echo ${{ steps.semver.outputs.nextStrict }}
          echo ${{ steps.semver.outputs.nextMajor }}
          echo ${{ steps.semver.outputs.nextMajorStrict }}
          echo ${{ steps.server.outputs.bump }}
      
      - name: Create tag
        id: tagger
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display TAGGER Outputs
        run: |
          echo "${{ steps.tagger.outputs.new_tag }}"
          echo "${{ steps.tagger.outputs.new_version }}"
          echo "${{ steps.tagger.outputs.pervious_tag }}"
          echo "${{ steps.tagger.outputs.previous_version }}"
          echo "${{ steps.tagger.outputs.release_type }}"
          echo "${{ steps.tagger.outputs.changelog }}"

