name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
    
      - name: Create tag
        id: tagger
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display TAGGER Outputs
        run: |
          echo "${{ steps.tagger.outputs.new_tag }}"
          echo "${{ steps.tagger.outputs.new_version }}"
          echo "${{ steps.tagger.outputs.pervious_tag }}"
          echo "${{ steps.tagger.outputs.previous_version }}"
          echo "${{ steps.tagger.outputs.release_type }}"
          echo "${{ steps.tagger.outputs.changelog }}"

      - name: Create a GH release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tagger.outputs.new_tag }}
          name: Release ${{ steps.tagger.outputs.new_tag }}
          body: ${{ steps.tagger.outputs.changelog }}
          generateReleaseNotes: true

